const initialAhzab = [
  { id: 1, title: "الفاتحة", completed: false },
  { id: 2, title: "وإذا لقوا", completed: false },
  { id: 3, title: "سيقول السفهاء", completed: false },
  { id: 4, title: "واذكروا الله", completed: false },
  { id: 5, title: "تلك الرسل", completed: false },
  { id: 6, title: "قل اونبئكم", completed: false },
  { id: 7, title: "لن تنالوا", completed: false },
  { id: 8, title: "يستبشرون", completed: false },
  { id: 9, title: "والمحصنات", completed: false },
  { id: 10, title: "الله لا إله إلا هو", completed: false },
  { id: 11, title: "لا يحب", completed: false },
  { id: 12, title: "قال رجلان", completed: false },
  { id: 13, title: "لتجدن", completed: false },
  { id: 14, title: "إنما يستجيب", completed: false },
  { id: 15, title: "ولو أننا نزلنا", completed: false },
  { id: 16, title: "المص", completed: false },
  { id: 17, title: "قال الملأ", completed: false },
  { id: 18, title: "وإذ نتقنا", completed: false },
  { id: 19, title: "واعلموا", completed: false },
  { id: 20, title: "إن كثيرًا", completed: false },
  { id: 21, title: "إنما السبيل", completed: false },
  { id: 22, title: "للذين أحسنوا", completed: false },
  { id: 23, title: "وما من دابة", completed: false },
  { id: 24, title: "وإلى مدين", completed: false },
  { id: 25, title: "وما أبرئ", completed: false },
  { id: 26, title: "أفمن يعلم", completed: false },
  { id: 27, title: "الر", completed: false },
  { id: 28, title: "وقال الله", completed: false },
  { id: 29, title: "سبحان", completed: false },
  { id: 30, title: "أولم يروا", completed: false },
  { id: 31, title: "قال ألم أقل", completed: false },
  { id: 32, title: "طه", completed: false },
  { id: 33, title: "اقترب", completed: false },
  { id: 34, title: "يا أيها الناس", completed: false },
  { id: 35, title: "قد أفلح", completed: false },
  { id: 36, title: "لا تتبعوا", completed: false },
  { id: 37, title: "وقال الذين لا يرجون", completed: false },
  { id: 38, title: "قالوا أنؤمن", completed: false },
  { id: 39, title: "فما كان جواب", completed: false },
  { id: 40, title: "ولقد وصلنا", completed: false },
  { id: 41, title: "ولا تجادلوا", completed: false },
  { id: 42, title: "ومن يسلم", completed: false },
  { id: 43, title: "ومن يقنت", completed: false },
  { id: 44, title: "قل من يرزقكم", completed: false },
  { id: 45, title: "وما أنزلنا", completed: false },
  { id: 46, title: "فنبذناه", completed: false },
  { id: 47, title: "فمن أظلم", completed: false },
  { id: 48, title: "ويقوم", completed: false },
  { id: 49, title: "إليه يرد", completed: false },
  { id: 50, title: "قل أولو جئتكم", completed: false },
  { id: 51, title: "ما خلقنا", completed: false },
  { id: 52, title: "لقد رضي", completed: false },
  { id: 53, title: "قال فما خطبكم", completed: false },
  { id: 54, title: "الرحمن", completed: false },
  { id: 55, title: "المجادلة", completed: false },
  { id: 56, title: "الجمعة", completed: false },
  { id: 57, title: "تبارك", completed: false },
  { id: 58, title: "قل أوحي", completed: false },
  { id: 59, title: "عم", completed: false },
  { id: 60, title: "سبح", completed: false },
];

export default initialAhzab;