const initialAjzaa = [
  { id: 1, title: "الجزء الأول", completed: false },
  { id: 2, title: "الجزء الثاني", completed: false },
  { id: 3, title: "الجزء الثالث", completed: false },
  { id: 4, title: "الجزء الرابع", completed: false },
  { id: 5, title: "الجزء الخامس", completed: false },
  { id: 6, title: "الجزء السادس", completed: false },
  { id: 7, title: "الجزء السابع", completed: false },
  { id: 8, title: "الجزء الثامن", completed: false },
  { id: 9, title: "الجزء التاسع", completed: false },
  { id: 10, title: "الجزء العاشر", completed: false },
  { id: 11, title: "الجزء الحادي عشر", completed: false },
  { id: 12, title: "الجزء الثاني عشر", completed: false },
  { id: 13, title: "الجزء الثالث عشر", completed: false },
  { id: 14, title: "الجزء الرابع عشر", completed: false },
  { id: 15, title: "الجزء الخامس عشر", completed: false },
  { id: 16, title: "الجزء السادس عشر", completed: false },
  { id: 17, title: "الجزء السابع عشر", completed: false },
  { id: 18, title: "الجزء الثامن عشر", completed: false },
  { id: 19, title: "الجزء التاسع عشر", completed: false },
  { id: 20, title: "الجزء العشرون", completed: false },
  { id: 21, title: "الجزء الحادي والعشرون", completed: false },
  { id: 22, title: "الجزء الثاني والعشرون", completed: false },
  { id: 23, title: "الجزء الثالث والعشرون", completed: false },
  { id: 24, title: "الجزء الرابع والعشرون", completed: false },
  { id: 25, title: "الجزء الخامس والعشرون", completed: false },
  { id: 26, title: "الجزء السادس والعشرون", completed: false },
  { id: 27, title: "الجزء السابع والعشرون", completed: false },
  { id: 28, title: "الجزء الثامن والعشرون", completed: false },
  { id: 29, title: "الجزء التاسع والعشرون", completed: false },
  { id: 30, title: "الجزء الثلاثون", completed: false },
];

export default initialAjzaa;